//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balaji_ERP_Solution.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costing
    {
        public int CostId { get; set; }
        public string Cost_Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
