//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balaji_ERP_Solution.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulationHeader
    {
        public int FormulationHeaderId { get; set; }
        public string FormulationName { get; set; }
        public Nullable<System.DateTime> FormulationDate { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string FormulationCode { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> FormulaQty { get; set; }
        public Nullable<int> attr1 { get; set; }
        public Nullable<bool> AcFlag { get; set; }
    }
}
