//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balaji_ERP_Solution.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public string PersonName { get; set; }
        public string PersonAddress { get; set; }
        public string PersonContact { get; set; }
        public string PersonEmail { get; set; }
    }
}
