//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balaji_ERP_Solution.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int PlantId { get; set; }
        public Nullable<int> ComapnyId { get; set; }
        public string PlantName { get; set; }
        public string Capacity { get; set; }
        public string PlantAddress { get; set; }
    }
}
