//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balaji_ERP_Solution.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseLine
    {
        public int PurchaseLineId { get; set; }
        public Nullable<int> PurchaseHeaderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> PackingId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
    }
}
