//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balaji_ERP_Solution.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        public int userid { get; set; }
        public string UserEmail { get; set; }
        public string UserPass { get; set; }
    }
}
