//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DataContext.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BalajiProductsManagementEntities : DbContext
    {
        public BalajiProductsManagementEntities()
            : base("name=BalajiProductsManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Costing> Costings { get; set; }
        public virtual DbSet<Godown> Godowns { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Packing> Packings { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Production> Productions { get; set; }
        public virtual DbSet<ProductionHeader> ProductionHeaders { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<PurchaseLine> PurchaseLines { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<GRNHeader> GRNHeaders { get; set; }
        public virtual DbSet<GRNLine> GRNLines { get; set; }
        public virtual DbSet<PurchaseHeader> PurchaseHeaders { get; set; }
        public virtual DbSet<FormulationHeader> FormulationHeaders { get; set; }
        public virtual DbSet<FormulationLine> FormulationLines { get; set; }
    
        public virtual ObjectResult<SpCompany_Result> SpCompany()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpCompany_Result>("SpCompany");
        }
    
        public virtual ObjectResult<SpCosting_Result> SpCosting()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpCosting_Result>("SpCosting");
        }
    
        public virtual ObjectResult<SpGodown_Result> SpGodown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGodown_Result>("SpGodown");
        }
    
        public virtual ObjectResult<SpItem_Result> SpItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpItem_Result>("SpItem");
        }
    
        public virtual ObjectResult<SpPacking_Result> SpPacking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpPacking_Result>("SpPacking");
        }
    
        public virtual ObjectResult<SpPerson_Result> SpPerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpPerson_Result>("SpPerson");
        }
    
        public virtual ObjectResult<SpPlant_Result> SpPlant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpPlant_Result>("SpPlant");
        }
    
        public virtual ObjectResult<SpProduct_Result> SpProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpProduct_Result>("SpProduct");
        }
    
        public virtual ObjectResult<SpProduction_Result> SpProduction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpProduction_Result>("SpProduction");
        }
    
        public virtual ObjectResult<SpProductionHeader_Result> SpProductionHeader()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpProductionHeader_Result>("SpProductionHeader");
        }
    
        public virtual ObjectResult<SpPurchaseHeader_Result> SpPurchaseHeader()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpPurchaseHeader_Result>("SpPurchaseHeader");
        }
    
        public virtual ObjectResult<SpTax_Result> SpTax()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpTax_Result>("SpTax");
        }
    
        public virtual ObjectResult<SpUnit_Result> SpUnit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpUnit_Result>("SpUnit");
        }
    
        public virtual ObjectResult<SpAllPurchase_Result> SpAllPurchase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAllPurchase_Result>("SpAllPurchase");
        }
    
        public virtual ObjectResult<SpDatewise_Result> SpDatewise(string fromdate, string toDate)
        {
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpDatewise_Result>("SpDatewise", fromdateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SpItemWiseDateWise_Result> SpItemWiseDateWise(Nullable<int> itemId, string fromDate, string toDate)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpItemWiseDateWise_Result>("SpItemWiseDateWise", itemIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SpProductWiseDateWise_Result> SpProductWiseDateWise(Nullable<int> productId, string fromDate, string toDate)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpProductWiseDateWise_Result>("SpProductWiseDateWise", productIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SpSupplierWise_Result> SpSupplierWise(Nullable<int> supplierId)
        {
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpSupplierWise_Result>("SpSupplierWise", supplierIdParameter);
        }
    
        public virtual int test(Nullable<int> s)
        {
            var sParameter = s.HasValue ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("test", sParameter);
        }
    
        public virtual ObjectResult<SpGetHeaderInfo_Result> SpGetHeaderInfo(Nullable<int> pOId)
        {
            var pOIdParameter = pOId.HasValue ?
                new ObjectParameter("POId", pOId) :
                new ObjectParameter("POId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetHeaderInfo_Result>("SpGetHeaderInfo", pOIdParameter);
        }
    
        public virtual ObjectResult<SpGRNLineData_Result> SpGRNLineData(Nullable<int> pOId)
        {
            var pOIdParameter = pOId.HasValue ?
                new ObjectParameter("POId", pOId) :
                new ObjectParameter("POId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGRNLineData_Result>("SpGRNLineData", pOIdParameter);
        }
    
        public virtual ObjectResult<SpSupplierwiseDatewise_Result> SpSupplierwiseDatewise(Nullable<int> supplierId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpSupplierwiseDatewise_Result>("SpSupplierwiseDatewise", supplierIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SpFormulationMax()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SpFormulationMax");
        }
    
        public virtual int Sp_Edit_Item()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Edit_Item");
        }
    
        public virtual int Sp_Edit_Material_Type(Nullable<int> client_id, Nullable<int> global_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Edit_Material_Type", client_idParameter, global_idParameter);
        }
    
        public virtual int Sp_Edit_Supplier(Nullable<int> client_id, Nullable<int> global_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Edit_Supplier", client_idParameter, global_idParameter);
        }
    
        public virtual int Sp_Edit_Tax_Type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Edit_Tax_Type");
        }
    
        public virtual int Sp_Line_Report_Update(Nullable<int> purchase_hedar, Nullable<int> global_id, Nullable<int> client_id)
        {
            var purchase_hedarParameter = purchase_hedar.HasValue ?
                new ObjectParameter("purchase_hedar", purchase_hedar) :
                new ObjectParameter("purchase_hedar", typeof(int));
    
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Line_Report_Update", purchase_hedarParameter, global_idParameter, client_idParameter);
        }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    
        public virtual int Sp_Purchase_Line_Detiels(Nullable<int> sale_hedar_id, Nullable<int> global_id, Nullable<int> client_id, Nullable<int> supplier_id)
        {
            var sale_hedar_idParameter = sale_hedar_id.HasValue ?
                new ObjectParameter("sale_hedar_id", sale_hedar_id) :
                new ObjectParameter("sale_hedar_id", typeof(int));
    
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            var supplier_idParameter = supplier_id.HasValue ?
                new ObjectParameter("supplier_id", supplier_id) :
                new ObjectParameter("supplier_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Purchase_Line_Detiels", sale_hedar_idParameter, global_idParameter, client_idParameter, supplier_idParameter);
        }
    
        public virtual int Sp_Purchase_Summery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Purchase_Summery");
        }
    
        public virtual int Sp_purchase_Summery_Update(Nullable<int> global_id, Nullable<int> client_id)
        {
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_purchase_Summery_Update", global_idParameter, client_idParameter);
        }
    
        public virtual int Sp_Sale_Hedar_rdlc_report(Nullable<int> client_id, Nullable<int> global_id, Nullable<int> sale_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            var sale_idParameter = sale_id.HasValue ?
                new ObjectParameter("Sale_id", sale_id) :
                new ObjectParameter("Sale_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Sale_Hedar_rdlc_report", client_idParameter, global_idParameter, sale_idParameter);
        }
    
        public virtual int Sp_Sale_Rdlc_Report(Nullable<int> sale_hedar_id, Nullable<int> global_id, Nullable<int> client_id)
        {
            var sale_hedar_idParameter = sale_hedar_id.HasValue ?
                new ObjectParameter("sale_hedar_id", sale_hedar_id) :
                new ObjectParameter("sale_hedar_id", typeof(int));
    
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Sale_Rdlc_Report", sale_hedar_idParameter, global_idParameter, client_idParameter);
        }
    
        public virtual int Sp_Sale_Rdlc_Report_View(Nullable<int> global_id, Nullable<int> client_id)
        {
            var global_idParameter = global_id.HasValue ?
                new ObjectParameter("global_id", global_id) :
                new ObjectParameter("global_id", typeof(int));
    
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Sale_Rdlc_Report_View", global_idParameter, client_idParameter);
        }
    }
}
