//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DataContext.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Godown
    {
        public int GodownId { get; set; }
        public Nullable<int> PlantId { get; set; }
        public string GodownName { get; set; }
        public string GodownAddress { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
