//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DataContext.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNLine
    {
        public int GRNLineId { get; set; }
        public Nullable<int> GRNHeaderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> POQty { get; set; }
        public Nullable<decimal> AcceptedQty { get; set; }
        public Nullable<decimal> RejectedQty { get; set; }
        public Nullable<decimal> FreeQty { get; set; }
        public Nullable<decimal> PORate { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<int> PurchaseLineId { get; set; }
    }
}
