//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DataContext.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionHeader
    {
        public int ProductionHeaderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
